travis:
  secure:
    BINSTAR_TOKEN: g/Qz6AeE6bwjPRTKhJC/dcSbe1+Rl5qKOblXg/+QNWtE+1BBjPp/wJWU+bWQnSpchMq/98gb7isubeTAQa6dPMAHY3K0qiM4Y/Ai8m9gn80j8FoTDRQzDT6SFYHhpeDAobIyZLcUshpBGTN7hVdEA97RK0Q6iNA7YB1DJszoYH63wACarRngntFRtW00YKVtlHVq/zm/KTV9YlYjDniNTxSNbU3sP2aIptBG+bL0pLnlzwLpO2Mftchyz/O29tl4tQrYw/EgnDD8vty9xRuvgiFZf0z8WWPlVaFw9f5j0SDprKDv6jORI8tqf9OpJu+nM2jONTJhzktm5v/OsiiWbG4h8kXbFx45H5mQrwmGX5FfHZc14s2GeDXeXVg35YPosECd+8BAANCkKYI0HIqdOZ7AuK0qvOA44wgu0qLh5u1jLQc51PmQK7JpBj+tlG2WYX28jlOoE5xxKtoBTIZCR673g1NyzQbzc3RH72jqq5lBe7BHNy4PJ6QGSSVBQ/UxGA/bfLAuk3NeU4OuuYVVpvEsw5ncl8m/3TUDYmJ2pyJTthj/6C4rxGIrCgWC4c+qZJst3r8/EviOs6vf3wiTw3kU3q8Z5XfVIxBlHIYRiOPQZ01ZM7s3yrnb7lcLqcRNn2iSir6EaPLyoLJ4RRKloOfUyyb6hKHl0bjXQI+cteo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
