travis:
  secure:
    BINSTAR_TOKEN: uTFlbkPVCXD/2YvfTR4zNRj/xXXNkuKhQAKLV49xrhgGhcppFMpwQT9WEcBbqJ0b0AtlzTywj3UkJ6iIp+xz8IUPv38H4xhoYgn9yZwq35fHo0DlcEmR1ttnbOf+uGfYPMlctu267we509lI8xn0o1E4Ndwi2Zocb2JrcMs7gIXouoJWgc5Ffoh+cwirccfat3RbG7p3yzdU0167Nr3oFwOmdqFeBz4bVWVIIsibOHKC17bJp78N17KDAir7eiJhtZp7fypMhyKqkE5n99N6MLO8Syle5uiojH8QlyMiTS0FEx1Lqrbc7SYZV404tLrmNzXuSgl5Fu8hXh7qipcHDo/TgtKR+bi+rx9EftLHVYhBPN7zMPo5h7dtFG8R6DGBagRiGmwcc1YXVvB4c/jydOtK2rWW/AXubuEFfk/rhD+OgkefcZYUiqwOM/ZQd4IJJ5PIiOZzx3XSho73mwjNnjC1QoQbxR81P+auDgtaHgMVOcCK/UbdLRIYdPIkadKg2tXGRlLtvl6LNmqRp+IdNWU35xq9ol96Fm8wshvuH+iE/zjAGKcMPuvh4EhoPVeszlN+HVMOpsbXU98xx2Rd9MfJKV7uffYR5u8vbKazQJ1h80cPam1AEhPf+PPoWSL2vKYogF0HkQj0/EI7xMZ7QvpBoKqqWxx40snX9az0KzE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
